### ISSUE TITLE
很喜欢你这个主题，求指点

### ISSUE THREAD

**Issue by wonux** [farseerfc/farseerfc#5]
很喜欢你这个主题，请问是你github中的bootstrap3吗？

我clone了你的bootstrap3主题，使用的时候插件报错，需要什么依赖么？

**Comment by farseerfc** [comment]
嗯是我的 fork 的 https://github.com/farseerfc/pelican-bootstrap3 。
要注意同時我有 fork 一堆插件 https://github.com/farseerfc/pelican-plugins ，配置文件也公開在這個 repo 裏了，用到了這些插件 https://github.com/farseerfc/farseerfc/blob/master/pelicanconf.py#L81 。寫的時候沒怎麼考慮兼容別的插件，或者沒考慮插件不在的情況，所以可能需要調整一下各種細節。
如果你用的時候遇到什麼報錯，把報錯貼過來，我可以看看問題在哪兒。

**Comment by wonux** [comment]
谢谢，我再试试。我写文章用的markdown，不是.rst，需要更改插件吗？

**Comment by farseerfc** [comment]
我用的大部分插件都是和 rst 無關的，"plantuml", "youku", "youtube", 'twitter_bootstrap_rst_directives' 這幾個可能是 rst 相關的。

**Comment by wonux** [comment]
> CRITICAL: UndefinedError: 'gettext' is undefined

gettext在哪里？

**Comment by farseerfc** [comment]
jinja 的 i18n 插件 https://farseerfc.me/redesign-pelican-theme.html#id51
配置裏寫這個：
https://github.com/farseerfc/farseerfc/blob/master/pelicanconf.py#L111

**Comment by wonux** [comment]
我不需要翻译功能，只要简体中文就可以了，去掉i18n插件，需要改的文件多吗，除了base.html还有什么吗

**Comment by wonux** [comment]
我之前加了JINJA_EXTENSIONS = ['jinja2.ext.i18n']这行也报同样的错误

**Comment by farseerfc** [comment]
除了 jinja 的那個插件還需要 pelican 的 i18n-subsites 插件配合。
嘛不用的話，大概所有模板都要稍微改改，因爲所有文本都是可翻譯的……
不過好在要改的地方都有明確記錄：
https://github.com/farseerfc/pelican-bootstrap3/blob/master/translations/zh_CN/LC_MESSAGES/messages.po
照這裏改，需要改每個翻譯記錄，行號在文件名後面，把用 gettext 的地方都改成直接寫簡體中文的就可以了。
