### ISSUE TITLE
生成 PNG 是在玩啥?

### ISSUE THREAD

**Issue by ghost** [farseerfc/farseerfc#6]
http://farseerfc.me/try-pelican.png

没有标题啊 😂😂

还有下面代码框里的滚动条是咋回事啊 😂😂😂

**Comment by farseerfc** [comment]
原本是用來一鍵轉發長微博的，可惜 weibo api 又卡又老而且和 https 的相性不好就去掉了這個按鈕只留下了 png ……

**Comment by ghost** [comment]
:joy::joy::joy:
